### ISSUE TITLE
RESEARCH social cost ($) from carbon emission (with time)

### ISSUE THREAD

**Issue by hoernschen** [hoernschen/grasp#2]
Search for good literatur

How could time be a factor here? How many output values should be there?

**Comment by tr1ng0** [comment]
I was maybe thinking the typical ESG goals to make this more aligned: current price, 2030, 2040, 2100?
whats your opinion on this?

**Comment by hoernschen** [comment]
Yes that is a very good idea. Maybe also 2050?

**Comment by tr1ng0** [comment]
This Paper perfectly addresses this, even though there are many variables and options, this is very recent paper (2024):
https://www.pnas.org/doi/abs/10.1073/pnas.2312030121

Table 2. Social cost of carbon, alternative scenarios (2019$/tCO2)
| Scenario      | 2020 | 2025 | 2050 |
|---------------|------|------|------|
| C/B optimal   | 50   | 59   | 125  |
| T < 2 °C      | 75   | 89   | 213  |
| T < 1.5 °C    | 3,557| 4,185| 16,552|
| Alt damage    | 124  | 146  | 281  |
| Paris extended| 61   | 72   | 159  |
| Base          | 66   | 78   | 175  |
| R = 5%        | 32   | 37   | 74   |
| R = 4%        | 49   | 58   | 107  |
| R = 3%        | 87   | 102  | 172  |
| R = 2%        | 176  | 207  | 302  |
| R = 1%        | 485  | 571  | 695  |

I would propose the T < 1,5*C number, due to it's direct link to the paris agreement, of which a majority of western country apparently committed to, but fail to achieve.
